name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      MICROCMS_API_URL: ${{ secrets.MICROCMS_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
        working-directory: app
      - run: pnpm run build
        working-directory: app
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        if: github.event_name == 'push'
        run: pnpm install
        working-directory: app
      - name: Build
        if: github.event_name == 'push'
        run: pnpm run build
        working-directory: app
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
